---
title: "Making the random draw"
format: docx
editor: visual
---

## Making the draw....

```{r}

## Random draw with replacement across entire sample

library(tidyverse)

Unique_sequences_ptarmigan <- rep(c("0-15-30", 
                                "0-30-15", 
                                "15-0-30",
                                "15-30-0",
                                "30-0-15",
                                "30-15-0"), 
                                each=6)

eu <- readRDS("./data/study_units.RDS")

set.seed(270225)
Units_draws <- eu %>% select(name, species) %>%
              filter(species == "willow ptarmigan") %>%
              mutate(treatment = sample(Unique_sequences_ptarmigan, 35, replace = FALSE))



```

```{r}

# Random draw with replacement within regions - WILLOW PTARMIGAN

library(tidyverse)

eu <- readRDS("./data/study_units.RDS")

Units_draws <- eu %>% select(name, species) %>%
  filter(species == "willow ptarmigan") %>%
  arrange(., name) %>%
  mutate(region = c("Troms", "Troms", "Midt", "Midt", "Nord", "Nord", "Nord", "Troms", 
                    "Nord", "Midt", "Sor", "Midt", "Midt", "Midt", "Midt", "Midt", "Midt", "Midt", "Sor", "Troms", "Nord", "Nord", "Nord", "Nord", 
                    "Troms", "Sor", "Midt", "Midt", 
                    "Nord", "Nord", "Nord", "Nord", "Nord", 
                    "Troms", "Troms"))

################################################################################
################################################################################

Unique_sequences_ptarmigan_midt <- rep(c("0-15-30", 
                                    "0-30-15", 
                                    "15-0-30",
                                    "15-30-0",
                                    "30-0-15",
                                    "30-15-0"), 
                                  each=2)
  set.seed(246)
  Midt_draw <- Units_draws %>% filter(region == "Midt") %>% 
  mutate(treatment = sample(Unique_sequences_ptarmigan_midt, 12, replace = FALSE))

################################################################################
################################################################################

  Unique_sequences_ptarmigan_nord <- rep(c("0-15-30", 
                                           "0-30-15", 
                                           "15-0-30",
                                           "15-30-0",
                                           "30-0-15",
                                           "30-15-0"), 
                                         each=3)
  set.seed(246)
  Nord_draw <- Units_draws %>% filter(region == "Nord") %>% 
    mutate(treatment = sample(Unique_sequences_ptarmigan_nord, 13, replace = FALSE))
  

################################################################################
################################################################################
  
  Unique_sequences_ptarmigan_troms <- rep(c("0-15-30", 
                                           "0-30-15", 
                                           "15-0-30",
                                           "15-30-0",
                                           "30-0-15",
                                           "30-15-0"), 
                                         each=2)
  set.seed(246)
  Troms_draw <- Units_draws %>% filter(region == "Troms") %>% 
    mutate(treatment = sample(Unique_sequences_ptarmigan_troms, 7, replace = FALSE))
  

################################################################################
################################################################################
  
  Unique_sequences_ptarmigan_south <- rep(c("0-15-30", 
                                            "0-30-15", 
                                            "15-0-30",
                                            "15-30-0",
                                            "30-0-15",
                                            "30-15-0"), 
                                          each=1)
  set.seed(246)
  South_draw <- Units_draws %>% filter(region == "Sor") %>% 
    mutate(treatment = sample(Unique_sequences_ptarmigan_south, 3, replace = FALSE))
  
################################################################################
################################################################################

  Units_draws_complete <- bind_rows(Midt_draw,Troms_draw, Nord_draw, South_draw)  
  kable(Units_draws_complete)
  
  



```

```{r}

# Random draw with replacement within regions - FOREST GROUSE

library(tidyverse)

eu <- readRDS("./data/study_units.RDS")

Units_draws_FG <- eu %>% select(name, species) %>%
  filter(species == "forest grouse") %>%
  arrange(., name) %>%
  mutate(region = c("Nord-Midt", "Nord-Midt", "Sor", "Sor", "Sor", "Sor", "Nord-Midt", "Ost", "Ost", "Ost", "Ost", "Ost", "Ost", "Nord-Midt", "Ost", "Ost", "Nord-Midt", "Nord-Midt", "Ost", "Ost", "Nord-Midt", "Nord-Midt", "Nord-Midt", "Ost", "Ost", "Ost", "Sor", "Sor", "Ost", "Ost"))

################################################################################
################################################################################

Unique_sequences_FG_nord_midt <- rep(c("0-10-20", 
                                    "0-20-10", 
                                    "10-0-20",
                                    "10-20-0",
                                    "20-0-10",
                                    "20-10-0"), 
                                  each=2)
set.seed(246)
Nord_Midt_draw_FG <- Units_draws_FG %>% filter(region == "Nord-Midt") %>% 
  mutate(treatment = sample(Unique_sequences_FG_nord_midt, 9, replace = FALSE))

################################################################################
################################################################################

Unique_sequences_FG_sor <- rep(c("0-10-20",
                                    "0-20-10", 
                                    "10-0-20",
                                    "10-20-0",
                                    "20-0-10",
                                    "20-10-0"), 
                                  each=1)
set.seed(246)
Sor_draw_FG <- Units_draws_FG %>% filter(region == "Sor") %>% 
  mutate(treatment = sample(Unique_sequences_FG_sor, 6, replace = FALSE))



################################################################################
################################################################################

Unique_sequences_FG_ost <- rep(c("0-10-20",
                                    "0-20-10", 
                                    "10-0-20",
                                    "10-20-0",
                                    "20-0-10",
                                    "20-10-0"), 
                                  each=3)
set.seed(246)
Ost_draw_FG <- Units_draws_FG %>% filter(region == "Ost") %>% 
  mutate(treatment = sample(Unique_sequences_FG_ost, 15, replace = FALSE))


################################################################################
################################################################################

Units_draws_complete_FG <- bind_rows(Nord_Midt_draw_FG,Sor_draw_FG, Ost_draw_FG)  
kable(Units_draws_complete_FG)
  
  



```
