---
title: "Supplementary Information"
format: html
editor: visual
---

## Appendix 1

Additional information about the systematic review:

**Decision tree for title and abstract screening:**

1.  Is there an abstract for the article? 

    a\) Yes - Go to 3. 

    b\) No - Go to 2 

2.  Can you find the abstract online? (Use google.com or Google Scholar to search for the title of the article) 

    a\) Yes - Enter the url for the website where you found the abstract in the ‘Add note’ box  and Go to 3 

    b\) No – Add/select ‘Abstract not found online’  in the ‘Exclude with Reason’ box. 

3.  Is the abstract in English/Norwegian/Danish/Swedish? 

    a\) Yes - Go to 4. 

    b\) No – Add/select ‘Abstract not in English/Norwegian/Danish/Swedish’  in the ‘Exclude with Reason’ box. 

4.  Does the abstract represent a research study focused on Galliformes? 

    a\) Yes - Go to 5 

    b\) No – Add/select ‘Not Galliformes’  in the ‘Exclude with Reason’ box. 

5.  Does the study document the effects of legal and/or managed harvest on Galliformes populations

    a\) Yes - Go  to 6 

    b\) No – Add/select ‘Not Hunting’  in the ‘Exclude with Reason’ box.

6.  Are effects assessed quantitatively? 

    a\) Yes – Press the include button

    b\) No - Add/select ‘Not quantitative’  in the ‘Exclude with Reason’ box.   

Data coding

From all papers that met the eligibility criteria, we extracted key variables (aka “data coding”). In addition to metadata about the publication (publication year, journal name etc) we extracted the following information:   

-   Species 

<!-- -->

-   Study area location 

<!-- -->

-   Country/countries 

<!-- -->

-   County/counties 

<!-- -->

-   Municipality/municipalities 

<!-- -->

-   Study extent / size of study area 

<!-- -->

-   Multinational 

<!-- -->

-   National 

<!-- -->

-   Regional (e.g. a county, a larger mountain area etc) 

<!-- -->

-   Local (e.g. a municipality or part of municipality) 

<!-- -->

-   Site level (\< 1km2) 

<!-- -->

-   Research type 

<!-- -->

-   Observational  / analyses of empirical data 

<!-- -->

-   Simulation based / scenario 

<!-- -->

-   Study design – observational studies 

<!-- -->

-   Randomized Controlled Trials (RCTs) 

<!-- -->

-   Before-After-Control-Impact (BACI) 

<!-- -->

-   Control-Impact (CA) 

<!-- -->

-   Before-After (BA) 

<!-- -->

-   After (A) 

<!-- -->

-   Harvest level 

<!-- -->

-   Reported harvest mortality 

<!-- -->

-   Assessment of additivity of harvest mortality 

<!-- -->

-   Boolean (Yes / No) 

<!-- -->

-   Outcome variables: EBV class 

<!-- -->

-   Genetic composition 

<!-- -->

-   Species population 

<!-- -->

-   Species trait 

<!-- -->

-   Outcome variable: EBV name \[not exhaustive; \* indicate name that is not included in original framework\] 

<!-- -->

-   Inbreeding 

<!-- -->

-   Effective population size 

<!-- -->

-   Species distribution 

<!-- -->

-   Species abundance 

<!-- -->

-   Population density \* 

<!-- -->

-   Morphology 

<!-- -->

-   Physiology 

<!-- -->

-   Movement rates\* 

<!-- -->

-   Habitat use / selection\* 

<!-- -->

-   Reproduction  

<!-- -->

-   Survival\* 

<!-- -->

-   Sex- and age structure\* 

## Appendix 2

List of eligible papers:

```{r}
#| echo: false
#| message: false
#| warning: false
library(synthesisr)
require(xtable)
require(tidyverse)
require(knitr)

data <- readRDS("data/GS_data_Raw.RDS")
data<-data |> 
  distinct(`Study ID`, .keep_all = TRUE)

excluded <- data |>
  filter(!rowSums(across(4:8, ~ . == "Yes")) == 5)
included <- anti_join(data, excluded)

all_RIS <- read_refs("data/articles.ris")

included_full_details <- left_join(included, all_RIS, by = c("Study ID" = "accession_zr"))

included_full_details <- included_full_details |> janitor::clean_names()


included_full_details |> 
  select(author,title,year,source,doi) |> 
  kableExtra::kable() |> 
  kableExtra::kable_styling()


```
